### ISSUE TITLE
Vue is not defined

### ISSUE THREAD

**Issue by tcarac** [borvelt/vuejs-microfrontend#1]
After including Dockerizing common and container I get vue is not defined.
Is this working ? 
app.e017001d.js:formatted:544 Uncaught ReferenceError: Vue is not defined

**Comment by borvelt** [comment]
Sorry for my delay to answer, It seems to be related to the docker containers network issue, by the way, I want to do big changes this week and then you can check it again. Thanks @tcaraccia-riv

**Comment by borvelt** [comment]
@tcaraccia-riv Did you test with new changes?

**Comment by panicboat** [comment]
The same was true for the latest version of 2020-09-27 (72eb2ac1cd9fd09c25ea4fb4ceb83af6f060c369).
It worked by removing the network and specifying localhost. Is this fix correct?
<details>
<summary>docker-compose.yml</summary>

```
version: '3.8'
services:
    mfe_renderer:
        container_name: mfe-renderer
        image: borvelt/mfe-renderer:latest
        command: npm start
        ports:
            - 8888
    mfe_vendors:
        container_name: mfe-vendors
        image: mfe-vendors
        build: vendors/
        command: yarn serve
        ports:
            - 8001:8001
    mfe_app_vehicles:
        container_name: mfe-app-vehicles
        image: mfe-app-vehicles
        build: vehicles/
        command: yarn serve
        ports:
            - 8002:8002
    mfe_container:
        container_name: mfe-container
        image: mfe-container
        build: 
            context: container/
            args:
                - VENDORS=http://localhost:8001/vendors.js
                - VUE_APP_VEHICLES_HOST=http://localhost:8002/
        command: yarn serve
        ports:
            - 8000:8000
        environment:
            - MFE_RENDERER=http://localhost:8888/render
```
</details>
